### ISSUE TITLE
Uninstalling a proxy server

### ISSUE THREAD

**Issue by doroved** [Theodikes/ipv6-proxy-server#11]
Make a backup of current configs before installing.
Add a command that will uninstall the proxy and rollback to the configs from the backup to get the same server state that was before the proxy was installed.

**Comment by Theodikes** [comment]
> Make a backup of current configs before installing. Add a command that will uninstall the proxy and rollback to the configs from the backup to get the same server state that was before the proxy was installed.

Done, closed with commit _[a0c3540cb4be4ca391a32e48f8739c7726409e80](https://github.com/Theodikes/ipv6-proxy-server/commit/a0c3540cb4be4ca391a32e48f8739c7726409e80)_.
