### ISSUE TITLE
netmask problem

### ISSUE THREAD

**Issue by erenctnky** [Theodikes/ipv6-proxy-server#19]
Hello
I am using /64 prefix but script generates
inet6 addr: xxxx:xxxx:xxx:x:3d39:42ca:3c4f:b41f/128 Scope:Global

isn't it supposed to be 
inet6 addr: xxxx:xxxx:xxx:x:3d39:42ca:3c4f:b41f/64 Scope:Global

**Comment by Theodikes** [comment]
Can you provide `proxyserver/3proxy/3proxy.cfg` content?

**Comment by Theodikes** [comment]
@erenctnky any updates?
