### ISSUE TITLE
502 Bad Gateway Error

### ISSUE THREAD

**Issue by fatihkabakk** [Theodikes/ipv6-proxy-server#2]
I have a vultr server.
I always get 502 Bad Gateway error.
I tried connection in python.
sudo ufw allow 30000 is done.

run command:
./ipv6-proxy-server.sh -s 64 -c 100 -u username -p password -t http -d

output:
IPv6 proxy server started successfully. Backconnect IPv4 is available from \<ip\>:30000:username:password to \<ip\>:30099:username:password via http protocol

```PYTHON
import requests

proxies = {'http': 'http://username:password@<ip>:30000', 'https': 'http://username:password@<ip>:30000'}

print(requests.get('http://ip-api.com/json/', proxies=proxies).content)
```

output:
```HTML
<html>
   <head>
      <title>502 Bad Gateway</title>
   </head>
   <body>
      <h2>502 Bad Gateway</h2>
      <h3>Host Not Found or connection failed</h3>
   </body>
</html>
```

**Comment by Theodikes** [comment]
_http://ip-api.com/json_ don't work with IPv6.
![curl not working](https://i.imgur.com/6vs4y1B.png)

Try, for example, _ipv6.ip.sb_ or [whatismyv6.com](http://whatismyv6.com/)
