### ISSUE TITLE
network/interface instead of netplan

### ISSUE THREAD

**Issue by jfrenl** [Theodikes/ipv6-proxy-server#20]
2024-03-01 22:50:40 (34.2 MB/s) - ‘ipv6-proxy-server.sh’ saved [26405/26405]

IPv6 interface is enabled
IPv6 global address is allocated on server successfully
Error: /etc/network/interfaces has no inet6 (IPv6) configuration.
It's because i use a /etc/network/interfaces 

How to solve?

**Comment by Theodikes** [comment]
Check readme please

**Comment by Theodikes** [comment]
Check readme please before writing an issue
