### ISSUE TITLE
IP v6 issues

### ISSUE THREAD

**Issue by gnouv** [Theodikes/ipv6-proxy-server#21]
Hi,

Thank you for this great script. But there are some things out there, if you know, please answer them for me because I'm just an end user, not a Cloud or network expert.

This script runs fine on an Ubuntu VPS from Vultr provider but if they find out I run multiple proxies on the VPS, they will ban my account.

So I want to run this script on another provider's VPS like Linode or Digital Ocean, but unfortunately it cannot be used because v6 IPs when created, they cannot be accessed from the internet, specifically I can not ping v6 IPs created by your script.

Is there some network configuration that needs to be changed?

Thanks.

**Comment by Theodikes** [comment]
I don't know about Linode, but DigitalOcean doesn't give you full /64 subnet - only 16 addresses.
For example:
![image](https://github.com/Theodikes/ipv6-proxy-server/assets/44587268/27845553-6654-4754-a7ab-b7d07d1ccc08)
