### ISSUE TITLE
Error: /etc/network/interfaces has no inet6 (IPv6) configuration.

### ISSUE THREAD

**Issue by testkings123** [Theodikes/ipv6-proxy-server#24]
What is the reason for this error, friends? Vultr

Error: /etc/network/interfaces has no inet6 (IPv6) configuration.

Very Thank You

**Comment by Theodikes** [comment]
Check please readme before writing an issue.
From readme: "`-d` or `--disable-inet6-ifaces-check` - disable /etc/network/interfaces configuration check & exit when error. Use only if configuration handled by cloud-init or something like this (for example, on Vultr servers), rarely used parameter, check your VPS documentation"
