### ISSUE TITLE
Error: IPv6 global address is not allocated on server, allocate it or contact your VPS/VDS support.

### ISSUE THREAD

**Issue by EconomicDead** [Theodikes/ipv6-proxy-server#26]
[root@Flippant-VM ~]# ./ipv6-proxy-server.sh -s 64 -c 100 -u username -p password -t http -r 10
IPv6 interface is enabled
Error: IPv6 global address is not allocated on server, allocate it or contact your VPS/VDS support.

uh can someone please help me😭

**Comment by erickythierry** [comment]
> [root@Flippant-VM ~]# ./ipv6-proxy-server.sh -s 64 -c 100 -u username -p password -t http -r 10 IPv6 interface is enabled Error: IPv6 global address is not allocated on server, allocate it or contact your VPS/VDS support.
> 
> uh can someone please help me😭

The error indicates that your server does not have a public IPv6 allocated.

**Comment by Theodikes** [comment]
This is your VDS problem, ask its support.

**Comment by duylddev** [comment]
I've tested on Vultr and DigitalOcean but none of them work
Anyone know which provider still support ipv6 global?
